---
title: "Final Project"
author: "Fabrizio Veneziano"
date: "Thursday, July 16, 2015"
output: html_document
---

##Getting the data

The training data set can be found on the following URL:

```{r LoadTrain, cache=TRUE}
trainUrl <- read.csv("http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv")

```


The testing data set can be found on the following URL:

```{r LoadTest, cache=TRUE}

testUrl <- read.csv("http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv")

```


```{r CleanUp}

names(trainUrl)

training <- trainUrl[,c(8:160)]

names(testUrl)

tests20 <- testUrl[,c(8:160)]


training <- training[, colSums(is.na(training)) == 0] 
tests20 <- tests20[, colSums(is.na(tests20)) == 0] 

#training <- na.omit(training)

```


```{r RattelFit}

library(rattle)

rattle()

```



```{r ModelFit}
library(caret)
library(ParallelForest)


set.seed(1234) 
inTrain <- createDataPartition(training$classe, p=0.80, list=F)
trainData <- training[inTrain, ]
testData <- training[-inTrain, ]

modFit <- train(classe~.,data=trainData, method="rf", trControl = trainControl(method = "cv"), ntree=200)



```


```{r Predict}

predictions <- predict(modFit, testData)
confusionMatrix(testData$classe, predictions)

accuracy <- postResample(predictions, testData$classe)
accuracy

oose <- 1 - as.numeric(confusionMatrix(testData$classe, predictions)$overall[1])
oose

```

